python main.py 'strategy=random' 'balance=False' 'select_batch_size=25' 'preprocess=True' 'split=True' 
python main.py 'strategy=random' 'balance=False' 'select_batch_size=50' 
python main.py 'strategy=random' 'balance=False' 'select_batch_size=75' 
python main.py 'strategy=random' 'balance=False' 'select_batch_size=100' 
python main.py 'strategy=random' 'balance=False' 'select_batch_size=125' 
python main.py 'strategy=random' 'balance=False' 'select_batch_size=150' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=False' 'select_batch_size=25' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=False' 'select_batch_size=50' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=False' 'select_batch_size=75' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=False' 'select_batch_size=100' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=False' 'select_batch_size=125' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=False' 'select_batch_size=150' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=25' 'pre_batch_size=50' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=50' 'pre_batch_size=100' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=75' 'pre_batch_size=150' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=100' 'pre_batch_size=200' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=125' 'pre_batch_size=250' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=150' 'pre_batch_size=300' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=25' 'pre_batch_size=75' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=50' 'pre_batch_size=150' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=75' 'pre_batch_size=225' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=100' 'pre_batch_size=300' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=125' 'pre_batch_size=375' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=150' 'pre_batch_size=450' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=25' 'pre_batch_size=100' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=50' 'pre_batch_size=200' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=75' 'pre_batch_size=300' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=100' 'pre_batch_size=400' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=125' 'pre_batch_size=500' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=150' 'pre_batch_size=600' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=25' 'pre_batch_size=125' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=50' 'pre_batch_size=250' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=75' 'pre_batch_size=375' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=100' 'pre_batch_size=500' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=125' 'pre_batch_size=625' 
python main.py 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 'balance=True' 'select_batch_size=150' 'pre_batch_size=750'
