python main.py 'balance=False' 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 
python main.py 'balance=True' 'strategy=uncertainty' 'strategy.type=_entropy_sampling' 
python main.py 'balance=False' 'strategy=bald' 
python main.py 'balance=True' 'strategy=bald'
python main.py 'balance=False' 'strategy=uncertainty' 'strategy.type=_margin_sampling' 
python main.py 'balance=True' 'strategy=uncertainty' 'strategy.type=_margin_sampling' 
python main.py 'balance=False' 'strategy=uncertainty' 'strategy.type=_least_confident' 
python main.py 'balance=True' 'strategy=uncertainty' 'strategy.type=_least_confident' 
python main.py 'balance=False' 'strategy=random'